name: Build and publish Docker image
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    # --- PERMISSIONS BLOCK ---
    permissions:
      contents: read
      packages: write # This line is essential
    # ------------------------------------

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/green-ai-tracker:latest
